# IOStack Crystal settings
IOSTACK_KEYSTONE_ADMIN_USER = 'changeme'
IOSTACK_KEYSTONE_ADMIN_PASSWORD = 'changeme'  # noqa

IOSTACK_KEYSTONE_ADMIN_TENANT = 'changeme'

IOSTACK_CONTROLLER_HOST = 'controller'
IOSTACK_CONTROLLER_PORT = '9000'
IOSTACK_CONTROLLER_URL = "http://%s:%s" % (IOSTACK_CONTROLLER_HOST, IOSTACK_CONTROLLER_PORT)

IOSTACK_CONTROLLER_FILTERS_ENDPOINT = "%s/filters" % IOSTACK_CONTROLLER_URL

IOSTACK_MONITORING_PROJECTS_PLOT = "8bbee064c047783ca4291a753f8b9de5"
IOSTACK_MONITORING_CONTAINERS_PLOT = "2ae44faeb23d79830a8ad4e6463b9e2b"
IOSTACK_MONITORING_SYSTEM_PLOT = "b321d4a2f933d826c9bd8acd530f543a"