# Crystal settings
CRYSTAL_ADMIN_PROJECT = 'management'

CRYSTAL_CONTROLLER_HOST = 'controller'
CRYSTAL_CONTROLLER_PORT = '9000'
IOSTACK_CONTROLLER_URL = "http://%s:%s" % (CRYSTAL_CONTROLLER_HOST, CRYSTAL_CONTROLLER_PORT)

KIBANA_PORT = '5601'
CRYSTAL_MONITORING_DASHBOARD = ""

SPARK_DASHBOARD_URL = "http://127.0.0.1:8080/"
SPARK_HISTORY_SERVER_URL = "http://127.0.0.1:18080/"
FLINK_DASHBOARD_URL = "http://127.0.0.1:8081/"
