# Crystal settings
IOSTACK_KEYSTONE_ADMIN_USER = 'manager'
IOSTACK_KEYSTONE_ADMIN_PASSWORD = 'manager'  # noqa

IOSTACK_KEYSTONE_ADMIN_TENANT = 'management'

IOSTACK_CONTROLLER_HOST = 'controller'
IOSTACK_CONTROLLER_PORT = '9000'
IOSTACK_CONTROLLER_URL = "http://%s:%s" % (IOSTACK_CONTROLLER_HOST, IOSTACK_CONTROLLER_PORT)

KIBANA_PORT = '5601'
CRYSTAL_MONITORING_DASHBOARD = ""

SPARK_DASHBOARD_URL = "http://127.0.0.1:8080/"
SPARK_HISTORY_SERVER_URL = "http://127.0.0.1:18080/"
FLINK_DASHBOARD_URL = "http://127.0.0.1:8081/"
